---
# pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer

  # ____________________________Yaml____________________________
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-d, "{rules: {line-length: disable}}"]
  #        args: [-c=.yamllint]

  # ____________________________Security____________________________
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.497
    hooks:
      - id: checkov
        args: [-d .]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  # ____________________________K8s____________________________
  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
    rev: v0.2.0
    hooks:
      - id: k8svalidate
        files: .yaml$
  # ____________________________Terraform____________________________
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_fmt
        args: [-recursive]
      - id: terraform_validate
        args: [-recursive]
      - id: terraform_tflint
        args: [-recursive]
      - id: terraform_docs
        args: [-recursive]
  # ____________________________Languages____________________________
  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  # Go
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
#      - id: go-vet
