apiVersion: app.example.com/v1alpha1
kind: ServiceMonitoring
metadata:
  labels:
    app.kubernetes.io/name: auto-observability-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicemonitoring-sample
spec:
  # TODO(user): Add fields here
